### ISSUE TITLE
spring-data-jpa 逻辑删除显示

### ISSUE THREAD

**Issue by chenboxiang** [springside/springside4#119]
能否增加下spring-data-jpa逻辑删除的演示，就是说delete只是update某个固定的标志位，另外find的时候能统一过滤掉被delete的entity，我现在是按照官网的方法自定义的全局的repository实现。不过我不知道如何接管业务自己的repository接口中定义的诸如“findByName”之类的方法

**Comment by mj19910923** [comment]
findBy 不满足？
