### ISSUE TITLE
J2EE爱好者发来4.1版本建议

### ISSUE THREAD

**Issue by gumutianqi** [springside/springside4#149]
###### 我对4.1的一些建议：
1. 加入https协议支持，直接集成在spring中，可结合jetty一起配置。
2. 加入请求url加密，已适应一些BOSS安全管理系统的开发需求。
3. 集成spring最新的ETag，可以配合nginx配置，也可在spring中独立使用。
4. 集成开源图片处理工具：java-image-scaling，对图片进行各种等比压缩，水印等各种工具。
5. AES加密组建建议改用：org.bouncycastle，可以支持更多更广泛的密钥填充方式。
6. 能否引入Velocity 模版引擎，有时候这东西还不错，提供个可选的模版引擎吧。
7. ......

### 暂时就想到这么多了，有想到的再来更新。

**Comment by mj19910923** [comment]
完全没搞懂各位为什么要吧这样的需求加入框架
