### ISSUE TITLE
Crypto模块增强

### ISSUE THREAD

**Issue by ghost** [springside/springside4#23]
AES支持IV(初始变量), SHA1支持Salt(盐值)，让相同的原文能加密出不同密文，增加安全性。

**Comment by shycool** [comment]
AES模块解密部分有bug，最后返回String没有指定编码，有中文的情况下（项目和ide，tomcat编码均为utf8），main方法和junit测试解密无问题，在tomcat下解密乱码,最后返回的String加上参数编码就可以了
	public static String aesDecrypt(byte[] input, byte[] key, byte[] iv) {
		byte[] decryptResult = aes(input, key, iv, Cipher.DECRYPT_MODE);
		return new String(decryptResult);
	}
