### ISSUE TITLE
modules 中的几个install.bat都下载不了对应的包

### ISSUE THREAD

**Issue by FengXMGeek** [springside/springside4#439]
白衣大神和其他大神你们好，我在搭建springside4（最新版）的时候出了问题。希望这个大神能不能帮下我。
除了parent可以下载对应的jar
其他的都是
bulid failure
[ERROR] Failed to execute goal on project springside-core: Could not resolve dep
endencies for project io.springside:springside-core:jar:4.3.0-SNAPSHOT: The foll
owing artifacts could not be resolved: io.springside:springside-utils:jar:4.3.0-
SNAPSHOT, org.springframework:spring-context:jar:4.1.3.RELEASE, org.springframew
ork:spring-tx:jar:4.1.3.RELEASE, org.springframework:spring-core:jar:4.1.3.RELEA
SE, org.aspectj:aspectjrt:jar:1.8.4, org.springframework:spring-webmvc:jar:4.1.3
.RELEASE, org.springframework:spring-expression:jar:4.1.3.RELEASE, org.springfra
mework:spring-web:jar:4.1.3.RELEASE, com.google.guava:guava:jar:18.0, com.faster
xml.jackson.core:jackson-databind:jar:2.4.4, com.fasterxml.jackson.core:jackson-
core:jar:2.4.4, org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016, o
rg.apache.httpcomponents:httpclient:jar:4.3.6, org.assertj:assertj-core:jar:1.7.
0, org.mockito:mockito-core:jar:1.10.8, org.springframework:spring-test:jar:4.1.
3.RELEASE, org.powermock:powermock-module-junit4:jar:1.6.0, org.powermock:powerm
ock-module-junit4-common:jar:1.6.0, org.powermock:powermock-core:jar:1.6.0, org.
powermock:powermock-reflect:jar:1.6.0, org.powermock:powermock-api-mockito:jar:1
.6.0, org.powermock:powermock-api-support:jar:1.6.0, org.springframework:spring-
aop:jar:4.1.3.RELEASE: Failure to find io.springside:springside-utils:jar:4.3.0-
SNAPSHOT in http://192.168.5.13:8080/nexus-2.2-01/content/groups/public was cach
ed in the local repository, resolution will not be reattempted until the update
interval of mirrorId has elapsed or updates are forced -> [Help 1]

**Comment by kai8406** [comment]
先要将springside-utils等模块生成jar放到本地仓库.
找到模块下的bin然后install.
注意模块也有先后依赖..

**Comment by FengXMGeek** [comment]
回复kai8406 
恩恩，谢谢，按你的方法弄好了！
