### ISSUE TITLE
无法部署程序

### ISSUE THREAD

**Issue by tianshaokai** [springside/springside4#440]
我使用maven执行maven eclipse:eclipse 命令，下载jar包，总是失败是怎么回事啊？在maven仓库也没有找到springside 的jar包

**Comment by diguage** [comment]
你需要先在SpringSide的根目录下`maven install`，把SpringSide安装到本地仓库里面。

SpringSide在4.2.3以前没有发布到Maven的中央仓库，在开源中国的第三方参考有4.2.2（貌似还有其他版本，记不清了）。

喜讯：从4.2.4开始，应该会发布到Maven中央仓库。呵呵

**Comment by jacarrichan** [comment]
不要轻易执行 mvn  install ，因为项目打包后放进本地仓库， 这样本地仓库会越来越庞大。

**Comment by tianshaokai** [comment]
嗯嗯，好，太好了，大神们，我想和你一起学习，共同进步。
