### ISSUE TITLE
最新版的springside4 view 由jsp换成velocity，这样可行不？

### ISSUE THREAD

**Issue by FengXMGeek** [springside/springside4#441]
把下面
	
	<bean id="contentNegotiationManager" class="org.springframework.web.accept.ContentNegotiationManagerFactoryBean">
	    <property name="ignoreAcceptHeader" value="true" />
            <property name="defaultContentType" value="application/json" />
	    <property name="mediaTypes" >
	        <value>
	            json=application/json
	            xml=application/xml
	        </value>
	    </property>
	</bean>
	
	  
	<bean class="org.springframework.web.servlet.view.InternalResourceViewResolver">
		<property name="prefix" value="/WEB-INF/views/"/>
		<property name="suffix" value=".jsp"/>
	</bean>
换成
	
	<bean id="velocityViewResolver" class="org.springframework.web.servlet.view.velocity.VelocityViewResolver">
		<property name="cache" value="false" />
		<property name="prefix" value="/" />
		<property name="suffix" value=".html" />
		<property name="contentType">
			<value>text/html;charset=UTF-8</value>
		</property>
		<property name="dateToolAttribute">
			<value>dateTool</value>
		</property>
		<property name="numberToolAttribute">
			<value>numberTool</value>
		</property>
		<property name="toolboxConfigLocation">
			<value>/WEB-INF/classes/toolbox.xml</value>
		</property>
	</bean>

	
	<bean id="velocityConfig" class="org.springframework.web.servlet.view.velocity.VelocityConfigurer">
		
		<property name="configLocation" value="classpath:velocity.properties" />
		
		<property name="resourceLoaderPath" value="/template/" />
	</bean>
其中toolbox.xml为
<?xml version="1.0" encoding="UTF-8"?>
<toolbox>
	<tool forceRelative="true" includeRequestParams="true">
		<key>link</key>
		<scope>request</scope>
		<class>org.apache.velocity.tools.view.tools.LinkTool</class>
	</tool>
	<tool>
		<key>math</key>
		<scope>application</scope>
		<class>org.apache.velocity.tools.generic.MathTool</class>
	</tool>
	<tool>
		<key>loop</key>
		<scope>request</scope>
		<class>org.apache.velocity.tools.generic.LoopTool</class>
	</tool>
	<tool>
		<key>display</key>
		<scope>application</scope>
		<class>org.apache.velocity.tools.generic.DisplayTool</class>
	</tool>
	<tool>
		<key>esc</key>
		<scope>application</scope>
		<class>org.apache.velocity.tools.generic.EscapeTool</class>
	</tool>
	<tool>
		<key>html</key>
		<scope>application</scope>
		<class>com.chinaj.scf.utils.HtmlVelocityTool</class>
	</tool>
	<tool>
		<key>number</key>
		<scope>application</scope>
		<class>org.apache.velocity.tools.generic.NumberTool</class>
		<parameter name="format" value="#0.0" />
	</tool>
	<tool>
		<key>cookie</key>
		<scope>request</scope>
		<class>org.apache.velocity.tools.view.CookieTool</class>
	</tool>
	<tool>
	   <key>date</key>
	   <scope>application</scope>
	   <class>org.apache.velocity.tools.generic.DateTool</class>
	</tool>
</toolbox>

**Comment by diguage** [comment]
我看了 Spring Framework 的规划，到 5.X 版就会把对于 Velocity 的支持去掉。另外， Velocity 已经有好长时间没有维护了。不知是怎么回事。
