### ISSUE TITLE
sitemesh decorators 的excludes配置不生效

### ISSUE THREAD

**Issue by ElvisWen** [springside/springside4#448]
excludes配置中包含对api/*下所有页面的过滤<pattern>/api/*</pattern>，但是没有起作用，见附件截图
![1](https://cloud.githubusercontent.com/assets/1540296/6700696/71c7759c-cd4c-11e4-8da5-5eef259b48a3.png)

**Comment by Humbunklung** [comment]
sitemesh的excludes是不是对某些名字的路径是不起作用的（类似api，html等这些）？以前整合sitemesh的时候也遇到过这种情况，有些excludes的内容总是excludes不了，都纳入框架里去了。修改了名字就又可以了，比较怪异。

**Comment by ElvisWen** [comment]
查看源代码之后发现，excludes的patten不支持XXX/*这种过滤符，只能过滤某个具体的URL

**Comment by Humbunklung** [comment]
谢谢，我也回去看看我当时是怎么加excludes的，也许真是这样。
