### ISSUE TITLE
希望能新增一个多数据源的示例，谢谢。

### ISSUE THREAD

**Issue by yrain** [springside/springside4#453]
希望能新增一个多数据源的示例，谢谢。

**Comment by wolf8334** [comment]
我最近在做一个类似ETL的东西，已经实现了基于SpringSide的多数据源。最主要的就是配置两套JPA体系，从数据源开始就是两套。

**Comment by yrain** [comment]
目前我是使用atomikos实现的多数据源事务管理，不过atomikos的文档和应用太少了。还是想找个替代的方法。

**Comment by wolf8334** [comment]
自己配置几个数据源就可以了。简单又方便~
