### ISSUE TITLE
showcase执行报错

### ISSUE THREAD

**Issue by xiaofeng320** [springside/springside4#456]
执行showcaseserver时候报这个警告
17:21:29.459 [main] WARN  o.s.b.f.s.DefaultListableBeanFactory - Bean creation exception on FactoryBean type check: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'shiroFilter': Requested bean is currently in creation: Is there an unresolvable circular reference?
请问为什么

**Comment by wolf8334** [comment]
这是个warn诶亲。。。
