### ISSUE TITLE
关于spring-data-jpa中findBy参数为null的情况

### ISSUE THREAD

**Issue by ptzhuf** [springside/springside4#462]
白衣,你好. 由于在一般项目中需求很可能是一个查询表单, 十几个查询字段请求过来, 但是实际上后端只会根据其中有值字段进行数据库查询, 而为null的字段是不会被加入查询参数了..

但是使用spring-data-jpa的过程中发现,findByXXXXAndYYYYAndZZZZLike 之类的写法会直接把null值作为查询条件 变成  XXXX is null. 

如果在业务逻辑层进行查询参数判断, 再决定调用哪个方法, 就会导致repository接口里的方法快速膨胀, 如果是 10个参数 意味着要写10个参数进行随机组合的那么多个(55个)方法了....
就算是使用自定义的repository实现方法, 也是需要进行大量的代码编写.

不知道在 springside4中有没有解决这个问题呢? 或者是有什么比较优雅的方案?
关联问题 : https://jira.spring.io/browse/DATAJPA-209

**Comment by pyyxx123** [comment]
兄台，参考一下quickstart 中TaskService 里的动态查询条件组合 试试?

**Comment by mj19910923** [comment]
极端情况，极端处理，呵呵

**Comment by ptzhuf** [comment]
这个应该不极端吧... 绝大多数系统都是参数传空就不进行查询的情况吧...  参数为空还要查询 isNull的情况才叫做极端情况啊....

**Comment by ptzhuf** [comment]
QueryByExampleExecutor 最新的 spring data jpa 1.12.2以上出现这个了...
算是支持了.... Repository.findAll(Example.of(Object));

**Comment by lineuman** [comment]
同样遇到了，如果传过来的值为null,则后端不使用条件查询的问题

**Comment by tomoya92** [comment]
有解决办法了吗？
