### ISSUE TITLE
wiki中'4.2.2 八和九生版 ，窦大仙风格的发布版本" 链接挂了

### ISSUE THREAD

**Issue by LimitlessYou** [springside/springside4#466]
wiki中'4.2.2 八和九生版 ，窦大仙风格的发布版本" 链接挂了 请修正啊

**Comment by fireshort** [comment]
嗯，https://github.com/springside/springside4/archive/V4.2.2.GA.zip 里面的“V4.2.2.GA.zip”，应该是“v4.2.2.GA.zip”。
