### ISSUE TITLE
shiro登录后返回到登录页登录无法正常跳转

### ISSUE THREAD

**Issue by spuerFan** [springside/springside4#487]
第一次登录成功后，通过浏览器后退到登录页（or 重新访问登录页），再次登录一直跳转到登录页；
删除本地cookie sessionid信息后，可以正常登录跳转

**Comment by spuerFan** [comment]
已确认是shiro本身的问题，AuthenticatingFilter其isAccessAllowed方法逻辑有误：
：protected boolean isAccessAllowed(ServletRequest request, ServletResponse response, Object mappedValue) {
        return super.isAccessAllowed(request, response, mappedValue) || !this.isLoginRequest(request, response) && this.isPermissive(mappedValue);
    }
fix the bug:  自定义子类重写这个方法 将逻辑 修改为先判断是否为登录请求 再判断有无权限

**Comment by vinkii** [comment]
你怎么改的？代码发下看看（只要这个方法的），谢谢。
