### ISSUE TITLE
springside-examples POM报错： Non-resolvable parent POM for springside-parent:5.0.0-SNAPSHOT   

### ISSUE THREAD

**Issue by aaronuu** [springside/springside4#504]
谢谢作者分享！！希望越做越好，会一直关注！！
Description Resource    Path    Location    Type
Project build error: Non-resolvable parent POM for io.springside.examples:springside-examples:[unknown-version]: Could not find artifact io.springside:springside-parent:pom:5.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM pom.xml /springside-examples    line 5  Maven pom Loading Problem

**Comment by iwin4aids** [comment]
我也是报一样的错，希望尽快修复一下，最新的master中example的pom好像没清理干净，springside-parent这个依赖好像是上个版本里面的，现在5.0.0-snapshot中确是是不包含这个父pom的

**Comment by xusheng1987** [comment]
我这也是这个错

**Comment by cmysunny** [comment]
example 5.0.0 我也遇到这个问题，修复后的pom文件如下
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.springside</groupId>
		<artifactId>springside-project</artifactId>
		<version>5.0.0-SNAPSHOT</version>
		<relativePath>../</relativePath>
	</parent>
		
	<artifactId>springside-examples</artifactId>
	<name>Springside :: Examples</name>
	<packaging>pom</packaging>

	<modules>
		<module>boot-api</module>
		<module>boot-showcase</module>
	</modules>
</project>

**Comment by calvin1978** [comment]
已修复
