### ISSUE TITLE
maven项目导入时的命名问题

### ISSUE THREAD

**Issue by iwin4aids** [springside/springside4#505]
当前pom里面工程命名都是springside :: xxx :xxx 这种形式。
但貌似现在最新版本myecplise直接导入maven项目的时候默认用name做项目名，但是是不支持冒号的
所以每次总要手动改成springside-xxx-xxx 体验稍稍可以改进哈
支持白衣很久了从3.X一直跟过来的 继续加油！

**Comment by wangshuaikang** [comment]
这里的代码只是个框架吗？不是整个项目吧？

**Comment by calvin1978** [comment]
好的，一直没用myeclipse，不知道有这个限制。
