### ISSUE TITLE
FastList.java:[194,42] <匿名org.springside.modules.utils.collection.type.FastList$1>不是抽象的, 并且未覆盖java.util.Iterator中的抽象方法remove()

### ISSUE THREAD

**Issue by onyas** [springside/springside4#530]
看提交的log,刚加的这个fastList有问题~
springside4/modules/utils/src/main/java/org/springside/modules/utils/collection/type/FastList.java:[194,42] <匿名org.springside.modules.utils.collection.type.FastList$1>不是抽象的, 并且未覆盖java.util.Iterator中的抽象方法remove()

**Comment by calvin1978** [comment]
已修复，JDK8有remove的默认实现。

**Comment by calvin1978** [comment]
真正用户啊，欢迎加群
