### ISSUE TITLE
编译失败了

### ISSUE THREAD

**Issue by mozhuwanjieDEV** [springside/springside4#532]
运行根目录下的quick-start.sh 或 quick-start.bat

将modules安装到本地maven仓库
以开发模式启动BootApi应用

Results :

Failed tests:   getName(org.springside.modules.utils.io.FilePathUtilTest): expec
ted:<"[]abc.txt"> but was:<"[/a/d/b/]abc.txt">
  pathName(org.springside.modules.utils.io.FilePathUtilTest): expected:<"/abc/[]
ef"> but was:<"/abc/[\]ef">

Tests run: 138, Failures: 2, Errors: 0, Skipped: 0

**Comment by wolf8334** [comment]
本来想自己反馈这个问题的，原来已经有人反馈了。那我就来解答一下吧。
这个问题的原因，是因为楼主在windows环境下编译造成的。原始代码里是这样写的。

`assertThat(FilePathUtil.getFileName("/a/d/b/abc.txt")).isEqualTo("abc.txt");`    
而这个方法的实现，却是考虑了平台通用性的。  
`/**
	 * 获取文件名(不包含路径)
	 */
	public static String getFileName(@NotNull String fullName) {
		Validate.notEmpty(fullName);
		int last = fullName.lastIndexOf(Platforms.FILE_PATH_SEPARATOR_CHAR);
		return fullName.substring(last + 1);
	}`  

所以，如果是windows环境，就会有问题。可以自己改一下代码跑过去。  

`assertThat(FilePathUtil.getFileName("\a\d\b\abc.txt")).isEqualTo("abc.txt");`

**Comment by calvin1978** [comment]
已将Wolf8334的提交合并，欢迎加群
