### ISSUE TITLE
httprequest参数检查问题

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [springside/springside4#534]
spring对request的通用参数检查，如果出问题，是通过TypeMismatchException和MissingServletRequestParameterException爆出的，那，考虑到异常的创建开销，这种方案在高并发场景下的性能，值得信任吗？考虑到有人恶意用不符合条件的请求攻击。

**Comment by wolf8334** [comment]
如果创建异常的开销都可以掣肘应用的性能，那么此时我们应当称其为DDOS。

**Comment by calvin1978** [comment]
Spring MVC就别想高性能了。
