### ISSUE TITLE
写了一个测试页面

### ISSUE THREAD

**Issue by jnuc093** [springside/springside4#543]
[springside4 5.0.0-RC1 test https](https://jnuc093.github.io/b/pages/springside4/index.html)由于没有支持https所以只能点下面了

[springside4 5.0.0-RC1 test](http://hmcy.net/springside4/index.html) 

### 步骤一 在两个类上追加CrossOrigin配置

@CrossOrigin(maxAge = 3600)
public class AccountEndPoint {

@CrossOrigin(maxAge = 3600)
public class BookEndpoint {

### 代码如下

https://github.com/jnuc093/1_bccw_m/blob/5.0.0-RC1-1/index.html

https://github.com/jnuc093/1_bccw_m/blob/5.0.0-RC1-1/my-app.js

**Comment by calvin1978** [comment]
好的，谢谢提交，我看看。
