### ISSUE TITLE
assertThat的引用不明确  怎么处理

### ISSUE THREAD

**Issue by setsuna** [springside/springside4#549]
[Pre-Requirement] Makesure install JDK 7.0+ and set the JAVA_HOME.
[Pre-Requirement] Makesure install Maven 3.0.3+ and set the PATH.
[Step 1] Install all springside modules to local maven repository.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Springside :: Module :: Utils
[INFO] Springside :: Module :: Core
[INFO] Springside :: Module :: Metrics
[INFO] Springside :: Module
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Springside :: Module :: Utils 5.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ springside-utils ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ springside-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\springsideRepository\springside4-master\modules\utils\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ springside-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 78 source files to E:\springsideRepository\springside4-master\modules\utils\target\classes
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1511,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1535,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1537,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1541,66] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1542,32] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1543,35] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinTask.java:[1543,56] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[1032,38] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3230,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3327,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3329,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3333,66] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3334,32] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3335,35] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ForkJoinPool.java:[3335,56] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[712,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[731,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[733,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[737,66] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[738,32] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[739,35] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/CountedCompleter.java:[739,56] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[101,38] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[291,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[314,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[316,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[320,66] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[321,32] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[322,35] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/Striped64.java:[322,56] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[3144,38] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6245,34] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6287,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6289,28] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6293,66] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6294,32] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6295,35] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/concurrent/jsr166e/ConcurrentHashMapV8.java:[6295,56] sun.misc.Unsafe是内部专用 API, 可能会在未来发行版中删除
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/number/NumberUtil.java: E:\springsideRepository\springside4-master\modules\utils\src\main\java\org\springside\modules\utils\number\NumberUtil.java使用或覆盖了已过时的 API。
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/number/NumberUtil.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/reflect/MethodInvoker.java: 某些输入文件使用了未经检查或不安全的操作。
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/main/java/org/springside/modules/utils/reflect/MethodInvoker.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ springside-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ springside-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 63 source files to E:\springsideRepository\springside4-master\modules\utils\target\test-classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/time/DateUtilTest.java: 某些输入文件使用或覆盖了已过时的 API。
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/time/DateUtilTest.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/ListUtilTest.java: 某些输入文件使用了未经检查或不安全的操作。
[WARNING] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/ListUtilTest.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/ListUtilTest.java:[96,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/CollectionUtilTest.java:[50,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/CollectionUtilTest.java:[52,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[21,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[24,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[27,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[29,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[64,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[67,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[83,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[87,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[92,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[95,17] 对assertThat的引用不明确
  org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/concurrent/ThreadLocalContextTest.java:[28,43] 对println的引用不明确
  java.io.PrintStream 中的方法 println(char[]) 和 java.io.PrintStream 中的方法 println(java.lang.String) 都匹配
[INFO] 14 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Springside :: Module :: Utils ...................... FAILURE [  4.050 s]
[INFO] Springside :: Module :: Core ....................... SKIPPED
[INFO] Springside :: Module :: Metrics .................... SKIPPED
[INFO] Springside :: Module ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.144 s
[INFO] Finished at: 2017-02-20T14:18:56+08:00
[INFO] Final Memory: 22M/330M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project springside-utils: Compilation failure: Compilation failure:
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/ListUtilTest.java:[96,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/CollectionUtilTest.java:[50,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/collection/CollectionUtilTest.java:[52,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[21,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[24,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[27,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[29,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[64,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[67,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[83,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[87,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[92,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/reflect/ReflectionUtilTest.java:[95,17] 对assertThat的引用不明确
[ERROR] org.assertj.core.api.Assertions 中的方法 assertThat(java.net.URI) 和 org.assertj.core.api.Assertions 中的方法 assertThat(java.math.BigDecimal) 都匹配
[ERROR] /E:/springsideRepository/springside4-master/modules/utils/src/test/java/org/springside/modules/utils/concurrent/ThreadLocalContextTest.java:[28,43] 对println的引用不明确
[ERROR] java.io.PrintStream 中的方法 println(char[]) 和 java.io.PrintStream 中的方法 println(java.lang.String) 都匹配
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error Happen!!
请按任意键继续. . .

**Comment by wslm1132** [comment]
同样的问题，你解决了吗?

**Comment by setsuna** [comment]
@wslm1132 没有 估计问题太low了没人解答

**Comment by YaoZihuan** [comment]
utils模块编译时就过不了。。看下代码咯

**Comment by whiletoken** [comment]
是测试类报错了，在quick-start.bat里面call %MVN% clean install的后边加上 -DskipTests，跳过测试类就行了

**Comment by setsuna** [comment]
@whiletoken 测试类的那几个方法注释掉就好了 不过还是好奇java.math.BigDecimal java.net.URI assertThat的区别
